### ISSUE TITLE
Add /reload instruction

### ISSUE THREAD

**Issue by x1aoren** [LewMC/Essence#101]
### What feature would you like to request?

This huge plugin doesn't have a reload command
This is very important, which means that every time I modify the configuration, I can only restart the server or use plugmanX

### Are you able to help implement the feature?

no

### Is your feature request related to an existing bug or issue?

no

### Please enter any additional comments below.

null

### Developer Tasks

- [x] Implement
- [x] Test Bukkit-based
- [x] Test Folia-based

**Comment by lewmilburn** [comment]
Added - snapshot version: https://github.com/LewMC/Essence/actions/runs/9733300033

**Comment by lewmilburn** [comment]
Added: https://github.com/LewMC/Essence/actions/runs/9733330264 (edit: fixed link)

**Comment by lewmilburn** [comment]
If you are able to assist, there are some outstanding translations from the new features including the /reload messages. https://crowdin.com/editor/lewmc-essence/26/en-zhcn?view=comfortable&filter=basic&value=2

**Comment by x1aoren** [comment]
I have made some modifications, with a completion rate of 99%. There is another one that I don't know the meaning of, and I dare not translate randomly.

**Comment by lewmilburn** [comment]
> I have made some modifications, with a completion rate of 99%. There is another one that I don't know the meaning of, and I dare not translate randomly.

Thank you! "Last known name" refers to the person's username the last time they logged in (since usernames can be changed).

**Comment by x1aoren** [comment]
Finish!

**Comment by lewmilburn** [comment]
> Finish!

Thank you! I've approved all your translations and set the one I'd mistakenly added as your correct version.
