### ISSUE TITLE
[BUG] /back /setspawn /spawn etc. cannot work

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [LewMC/Essence#126]
### Please describe the bug

command are not work as well

### Steps to reproduce the behavior

1. run command
2. saw server give back command(eg. /back)

### Expected behavior

command work well

### Server information:

Folia 1.20.6
Lastest Essence version

### Please enter a link to your logs

no logs

**Comment by lewmilburn** [comment]
Hi @xiaoyueyoqwq, please can you send me a list of plugins you're using, as well as the permissions you've given your players as I'm unable to reproduce the issue using the latest snapshot version of Essence and this may help with finding the problem. Thank you!

**Comment by xiaoyueyoqwq** [comment]
> Hi @xiaoyueyoqwq, please can you send me a list of plugins you're using, as well as the permissions you've given your players as I'm unable to reproduce the issue using the latest snapshot version of Essence and this may help with finding the problem. Thank you!

Hey, thanks for the reply
Maybe I just remembered something: I removed the rtp command in the plugin.yml because of the plugin problem, maybe it is that problem? I'm really not sure but I know the permission is not any problem

**Comment by xiaoyueyoqwq** [comment]
https://github.com/user-attachments/assets/24b80dd7-b0ef-44f3-beda-4a9a6a6a5c4d

Check this video

**Comment by lewmilburn** [comment]
Hi @xiaoyueyoqwq, thanks for the video! That looks like the default error that is thrown when a command is disabled in config.yml, could you check in the config if this is the case? Thank you!

**Comment by xiaoyueyoqwq** [comment]
> Hi @xiaoyueyoqwq, thanks for the video! That looks like the default error that is thrown when a command is disabled in config.yml, could you check in the config if this is the case? Thank you!

Okay I will check it, wait for the message🤔

**Comment by lewmilburn** [comment]
> > Hi @xiaoyueyoqwq, thanks for the video! That looks like the default error that is thrown when a command is disabled in config.yml, could you check in the config if this is the case? Thank you!
> 
> Okay I will check it, wait for the message🤔

Great thanks!

**Comment by xiaoyueyoqwq** [comment]
> > > Hi @xiaoyueyoqwq, thanks for the video! That looks like the default error that is thrown when a command is disabled in config.yml, could you check in the config if this is the case? Thank you!
> > 
> > Okay I will check it, wait for the message🤔
> 
> Great thanks!

I tested it and i know that problem is my fault, because I broke some important stuff in plugins.yml so some commands cannot work well, sorry about this issue 😣

**Comment by lewmilburn** [comment]
> > > > Hi @xiaoyueyoqwq, thanks for the video! That looks like the default error that is thrown when a command is disabled in config.yml, could you check in the config if this is the case? Thank you!
> > > 
> > > 
> > > Okay I will check it, wait for the message🤔
> > 
> > 
> > Great thanks!
> 
> I tested it and i know that problem is my fault, because I broke some important stuff in plugins.yml so some commands cannot work well, sorry about this issue 😣

No worries, glad you got it sorted! If you need anything else feel free to send me a message!
