### ISSUE TITLE
Information on join and exit prompts

### ISSUE THREAD

**Issue by x1aoren** [LewMC/Essence#134]
### What feature would you like to request?

I don't know why there are no message prompts for my server players to enter and exit
And I think this feature is also good, adding support for color codes and allowing modification of the addition and exit prompts in the configuration file. Hope to increase

### Are you able to help implement the feature?

inability

### Is your feature request related to an existing bug or issue?

No

### Please enter any additional comments below.

I love the author

**Comment by lewmilburn** [comment]
Done - You can download the snapshot that includes this at https://github.com/LewMC/Essence/actions/runs/9995254486
