### ISSUE TITLE
Unable to locate world in universe.

### ISSUE THREAD

**Issue by TheyCallMeLinux** [LewMC/Essence#145]
### Please describe the bug

Not sure if this is something I missing in the configuration but i'm currently facing a bug when I spawn back from the end dimension that appears to be related to: [/src/main/java/net/lewmc/essence/commands/teleportation/SpawnCommand.java](https://github.com/LewMC/Essence/blob/0a6391bcca27261a7e96800773dc4aecf34ef1d3/src/main/java/net/lewmc/essence/commands/teleportation/SpawnCommand.java#L84), function   Location teleportLocation; on lines 84

### Steps to reproduce the behavior

Player sets a respawn point with a bed.
The player goes to the_end dimension, 
Player takes Exit portal and comes back to overworld, no issue in general but gets an error visible in the logs. 

![image](https://github.com/user-attachments/assets/405d6b0e-d3c6-4c31-8e47-e855de037b8a)

Tested with admin privileges and i'm also getting the same error myself. 

### Expected behavior

Can respawn from the_end to overworld without error message

### Server information:

Minecraft Version: 1.21 - Server Implementation: Paper build #109 - Essence Version: 1.7.0

**Comment by lewmilburn** [comment]
Hi @TheyCallMeLinux, thanks for reporting! Are there any logs that show up in the server console? Thanks!

**Comment by TheyCallMeLinux** [comment]
Thanks for you reply. Here are the only two line that are printed in the logs

![image](https://github.com/user-attachments/assets/aa3f5fca-7a6b-452f-a513-e50b5c3e9ddb)

**Comment by lewmilburn** [comment]
Thanks! I'll have a look into this asap.

**Comment by lewmilburn** [comment]
Could you send me a copy of your config.yml please 😄  thanks!

**Comment by TheyCallMeLinux** [comment]
This happens with the default config with same name "world" for the map in the directory and inside server.properties iteself

**Comment by lewmilburn** [comment]
Great thanks! I’ll have a look into this after work and get back to you asap, might be a few hours tho!

**Comment by TheyCallMeLinux** [comment]
no rush, thanks a lot @lewmilburn !

**Comment by lewmilburn** [comment]
Hi sorry for taking a while to get back to you, I've had quite a crazy week - will try and look at this over the weekend and get back to you soon, sorry for the delay!

**Comment by lewmilburn** [comment]
Bug fixed and will be pushed in next update - you can download a snapshot build that includes the fix from [here](https://github.com/LewMC/Essence/actions/runs/10264371505) if you'd like it earlier. Thanks!
