### ISSUE TITLE
Simple `/tpa` command along with some others.

### ISSUE THREAD

**Issue by byteveil** [LewMC/Essence#21]
Here's the command setup:

```
/tpa [username]
/tpaccept [username]
/tpdeny [username]
/tptoggle [true/false]? (optional true or false otherwise just toggle)
```

Permissions file could have these entries available:

```
essence.teleportation.request
essence.teleportation.accept
essence.teleportation.deny
essence.teleportation.toggle
```

I'd rather Essence have `/tpa` because my server currently uses [LuckyTPA](https://modrinth.com/plugin/luckytpa-1.20.1) and the buttons in the chat encourage players to use them, but when someone has a different chat size they won't be able to use the buttons correctly.

**Comment by lewmilburn** [comment]
- [ ] /tpa [username]
- [ ] /tpaccept [username]
- [ ] /tpdeny [username]
- [ ] /tptoggle [true/false]
