### ISSUE TITLE
[Essence] Tried to close a file before one had been opened.

### ISSUE THREAD

**Issue by Quackified** [LewMC/Essence#65]
### Please describe the bug

Running on PaperMC 1.21 Build#4
Essence 1.5.0

It just won't set spawnpoint in the bed, teleporting back to spawn whenever a player dies.

### Steps to reproduce the behavior

Interact on a bed to set spawnpoint (No Respawn Point Set Message)
Kill Self
Returns Back to World Spawn

### Expected behavior

Respawn to Spawn Point (Bed)

### Server information:

Minecraft Version: [1.21] - Server Implementation: [PaperMC 1.21 Build#4] - Essence Version: [1.5.0]

### Anything else?

![image](https://github.com/LewMC/Essence/assets/87954493/f6389f1e-4b4c-4689-a929-23b3837384c0)
![image](https://github.com/LewMC/Essence/assets/87954493/90cd5a09-00d3-41f1-af0a-8d29895c404f)

**Comment by lewmilburn** [comment]
Thanks for reporting, I'll have a look ASAP

**Comment by lewmilburn** [comment]
@Quackified Respawning into beds should be fixed with the JAR available here: https://github.com/LewMC/Essence/actions/runs/9570862175 (might take a few mins after me sending this for it to appear)

**Comment by lewmilburn** [comment]
Not sure why that link isn't working - checked and this one does: https://service.lewmc.net/essence-1.5.1-SNAPSHOT.jar
