### ISSUE TITLE
Homes and Warps list malfunctioning.

### ISSUE THREAD

**Issue by lewmilburn** [LewMC/Essence#73]
### Please describe the bug

No warps created: `No warps.`
Warps created: `Warps: x, y, z`
Warps then deleted: `Warps:`

### Server information:

Since implemented.

**Comment by TheMightyBlurr** [comment]
/home, says you haven't set any homes even when you have multiple. should just list them instead

**Comment by lewmilburn** [comment]
> /home, says you haven't set any homes even when you have multiple. should just list them instead

Hi @TheMightyBlurr, thanks for reporting! Please could you send me the Essence player data file (/plugins/essence/data/players) for the player this is affecting. Thanks!

**Comment by TheMightyBlurr** [comment]
[fc31e3cb-1f24-4710-b93c-dc40b4ec037b.zip](https://github.com/user-attachments/files/15936363/fc31e3cb-1f24-4710-b93c-dc40b4ec037b.zip)

**Comment by lewmilburn** [comment]
> [fc31e3cb-1f24-4710-b93c-dc40b4ec037b.zip](https://github.com/user-attachments/files/15936363/fc31e3cb-1f24-4710-b93c-dc40b4ec037b.zip)

Thanks, I'll look into that, any errors or logs in the console when /homes is ran?

**Comment by lewmilburn** [comment]
@TheMightyBlurr, I'm not able to reproduce the issue on my end. Could you please send me the list of plugins and datapacks (if you have any) that you're running, as well as your Minecraft Version, Server Software, and Essence Version please. Thank you!

**Comment by lewmilburn** [comment]
This should have been fixed in #76, can you let me know if you're still experiencing this issue with this new Jar, and if you are please send the info requested above. Thanks!

[essence-1.5.3-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/15943779/essence-1.5.3-SNAPSHOT.jar.zip)
