### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by TheMightyBlurr** [LewMC/Essence#74]
### What feature would you like to request?

A way of limiting the amount of /sethome and /setwarps per ranks?

### Are you able to help implement the feature?

i can try but i've never done this

### Is your feature request related to an existing bug or issue?

no

**Comment by lewmilburn** [comment]
Thanks for the request! Should be able to get added in the next update.

**Comment by lewmilburn** [comment]
# Feature Added

- Homes can now be limited using the essence.home.limit.X
- Team Homes can now be limited using the essence.home.team.limit.X
- Warps can now be limited using the essence.warp.limit.X

Download: [essence-1.5.3-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/15959419/essence-1.5.3-SNAPSHOT.jar.zip)
_Please note, this jar also has other content from the upcoming update._

(Pinging @TheMightyBlurr)

# Wiki
## Warp and Home Creation Limits
By default, users can create as many warps and homes as they'd like. You can limit this by using permissions.

> :warning: If a user already has more homes than the limit before you apply it, this won't delete existing homes, it will just prevent the user from creating more.

Using this feature, you can define the number of homes a user can create by using a permissions plugin. This allows different ranks to have a different number of homes.

### Warps
By giving a user the permission `essence.warp.limit.1`, it will limit the user to creating only 1 warp. You can change the number to what you'd like to set the limit to.

### Homes
By giving a user the permission `essence.home.limit.1`, it will limit the user to creating only 1 home. You can change the number to what you'd like to set the limit to.

### Team Homes
By giving a user the permission `essence.home.team.limit.1`, it will limit the user to creating only 1 team home. You can change the number to what you'd like to set the limit to.

A user must already be a member of a team to create team homes, and team homes must be enabled in the team's rules.
