### ISSUE TITLE
Minor Bug report

### ISSUE THREAD

**Issue by TheMightyBlurr** [LewMC/Essence#77]
### Please describe the bug

Ill stipulate this is a very minor issue it just confused a few of my players
When having multiple '/home's and not one called 'home' doing /home will subsequently say "You havent set any homes"
![image](https://github.com/LewMC/Essence/assets/29232574/5582cdef-0ffa-4b6e-979e-114ed38c387e)
![image](https://github.com/LewMC/Essence/assets/29232574/126a2e64-07db-4784-a71d-125649bb18dc)

### Steps to reproduce the behavior

create multiple homes not called home. ie /sethome 1,2,3 and then do /home and leave the field empty.
I do have 3 seperate accounts doing this :)

### Expected behavior

I expected the command /home to work the same way the warps does and tell you how to use it properly or instead just list your homes.

### Server information:

Minecraft version 1.21
Paper version 1.21-27-master@76c2f16

### Please enter a link to your logs

There's not really any logs to give, it doesn't throw up any errors

### Anything else?

![image](https://github.com/LewMC/Essence/assets/29232574/4bed3982-e2af-4316-a6e8-256492e18415)

**Comment by TheMightyBlurr** [comment]
if I'm completely off the mark with this being a bug let me know. I'm new to this, however i couldn't find a #issues section on your discord or anything

**Comment by lewmilburn** [comment]
Thank you! I’m about to head off to work I’ll take a look when I get back.

> if I'm completely off the mark with this being a bug let me know. I'm new to this, however i couldn't find a #issues section on your discord or anything

This does look like a bug to me, thanks for reporting here! I’ll update the discord with a link to this repo so it’s easier to report in the future. Thanks!

**Comment by lewmilburn** [comment]
@TheMightyBlurr, fixed! If you'd like to get this feature early you can use this jar: [essence-1.5.3-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/15945413/essence-1.5.3-SNAPSHOT.jar.zip) or you can wait for the final version which will be out hopefully tomorrow or Tuesday.
