### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by TheMightyBlurr** [LewMC/Essence#85]
### What feature would you like to request?

An option for moving to cancel teleportation.

### Please enter any additional comments below.

Thanks for being so rapid with the other fixes/features I've asked for :)

### Developer Tasks

- [x] Implement
- [x] Test Bukkit-based
- [x] Test Folia-based
- [x] Add language key for moved.
- [x] Update language key to inform moving will cancel.

**Comment by lewmilburn** [comment]
Hi @TheMightyBlurr, very happy to add this but it might take a few days as I'm working pretty much all day every day until Monday. Will take a look after then, thank you for the request!

**Comment by lewmilburn** [comment]
Hi, I'm looking at adding this next! Sorry for taking so long!

_Note to self: https://www.spigotmc.org/threads/cancel-teleport-on-move.428122/_
