### ISSUE TITLE
The command should not be displayed and completed without authorization and time limit

### ISSUE THREAD

**Issue by x1aoren** [LewMC/Essence#96]
### What feature would you like to request?

The command should not be displayed and completed without authorization and time limit

### Are you able to help implement the feature?

unable

### Is your feature request related to an existing bug or issue?

It seems that there is no

### Please enter any additional comments below.

![37a3010457482bded2d6b1319c855fee](https://github.com/LewMC/Essence/assets/136235181/00a809d5-11d2-4517-8d53-237c188d98f0)
I don't want TPA functionality. Confirm that permissions have been disabled in Luckperms, but they will still be displayed here and support completion

**Comment by lewmilburn** [comment]
Hi @x1aoren, just to confirm are users able to enter the command and have it run without permissions? Thank you.

As a temporary workaround, you can disable the command in config.yml [[wiki](https://wiki.lewmc.net/es-disabling-commands.html)] I've provided an example below. This will prevent the command from being processed but it will still display as being available. I'll get the bug fixed ASAP.

Displaying of commands in the autocomplete list as you've shown in the screenshot is a more difficult one, as that's a server software thing. I'll see if I can sort that out too though!

```
disabled-commands:
  - tpa
  - tpahere
  - tpaccept
  - tpdeny
  - tpcancel
```

**Comment by lewmilburn** [comment]
Do you users have the essence.teleport.* permission? That will enable the request commands as well.

**Comment by x1aoren** [comment]
I understand now, looking forward to updates

**Comment by lewmilburn** [comment]
Glad to hear it! Did this fix your issue?

**Comment by x1aoren** [comment]
This doesn't seem to be very useful.

**Comment by lewmilburn** [comment]
Okay, I'll investigate further. Can you send me a list of all the permissions the players have? Thanks

**Comment by x1aoren** [comment]
![Uploading fd28d48b12f5c62fe67b57fc7dac2bf9.png…]()

**Comment by lewmilburn** [comment]
Thanks!

**Comment by lewmilburn** [comment]
Hi, I'm unable to recreate the issue on 1.6.0 on my end, please check the following:

1. User is not "op", this will allow them to run the command as "op" players can run everything.
2. Please send a list of plugins or datapacks you're running.
3. Please send your Essence versions
4. Please send your Minecraft server software version.

**Comment by x1aoren** [comment]
1. Confirm that the user is not an "OP"
2.
![36c9d7da-5475-40dc-8819-5313937f3c6f](https://github.com/LewMC/Essence/assets/136235181/f51135ba-318a-4285-b062-974033e373a9)

 "[S][禁用不安全服务器]AntiPopup-8.1": https://modrinth.com/plugin/antipopup
3.The version is 1.6.0
4.Luminol 1.20.6.
Official website: https://luminolmc.com/downloads/luminol
Download address: https://github.com/LuminolMC . Luminol is a branch of Folia, which fixed the damage of paper to the original features of MC. But currently 1.20.6 is a beta version, I don't know if this is the reason
5.If you want to reload all the configurations on the server, using/reload on this server will result in an error. So I usually use PlugmanX to hot load or uninstall plugins, or simply restart the server. At present, I have used all the above solutions and have not used them.

**Comment by lewmilburn** [comment]
Thanks! I won't have time to look at this fully and get back to you today, but I'll start looking now and get back to you tomorrow. Thanks!

**Comment by lewmilburn** [comment]
So sorry for the delay, having a look now!

**Comment by lewmilburn** [comment]
Hi @x1aoren, I've not been able to reproduce the issue on my end, but I've also been unable to get LuckPerms to load as my Luminol is telling me it doesn't support Folia, are you using a fork of LuckPerms that enables folia support?

**Comment by x1aoren** [comment]
I downloaded it from a certain link here. The version is a bit old, but it can be used.https://github.com/LuckPerms/LuckPerms/pull/3615

**Comment by x1aoren** [comment]
[[L][权限组]LuckPerms-Bukkit-5.4.117.zip](https://github.com/user-attachments/files/16117987/L.LuckPerms-Bukkit-5.4.117.zip)

**Comment by lewmilburn** [comment]
Thanks for that, I'm still unable to reproduce the bug on my end, so I'm not entirely sure what is going on with it. Are you still being affected by the issue?

**Comment by lewmilburn** [comment]
Does the issue produce anything in the logs that may be useful? Thank you :)

**Comment by x1aoren** [comment]
Yes, this problem still exists. No logs

**Comment by lewmilburn** [comment]
Please can you try this snapshot version https://github.com/LewMC/Essence/actions/runs/9852301534 and let me know if the issue is still there. A very small number of commands will still have the problem as I'm still working on the update.

**Comment by x1aoren** [comment]
I'm glad it's resolved!

**Comment by lewmilburn** [comment]
Glad that's sorted it! Upcoming snapshot builds should fix the problem further, and the next update will fully resolve the problem.
