### ISSUE TITLE
Reprint your plugin

### ISSUE THREAD

**Issue by x1aoren** [LewMC/Essence#97]
### What feature would you like to request?

Sorry for the trouble, I know Issues are not used that way
But the Chinese internet generally cannot access the chat software you are using, and using VPN may violate the law
There has been a significant change in the MC community in China this year, and I cannot explain the specifics
I opened an MC forum（ https://mcobs.fun/ ）. I would like to repost your plugin here, is that okay

### Are you able to help implement the feature?

SORRY

### Is your feature request related to an existing bug or issue?

SORRY

### Please enter any additional comments below.

SORRY for the trouble, I know Issues are not used that way
But the Chinese internet generally cannot access the chat software you are using, and using VPN may violate the law
There has been a significant change in the MC community in China this year, and I cannot explain the specifics
I opened an MC forum（ https://mcobs.fun/ ）. I would like to repost your plugin here, is that okay

**Comment by lewmilburn** [comment]
@x1aoren yes you can repost it there. Thank you for sharing the plugin, and thank you for asking!

**Comment by x1aoren** [comment]
Thank you.
